services:
  airflow:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags  # Mount the DAGs folder
      - ./logs:/opt/airflow/logs  # Mount the logs folder
      - ./src:/opt/airflow/dags/src  # Mount the src folder containing custom operators
      - ./requirements.txt:/opt/airflow/requirements.txt  # Mount the requirements file for pip install
      - ./variables.json:/opt/airflow/secrets.json  # Mount Airflow secrets
    restart: unless-stopped
    container_name: ${USER}-airflow-gh-example
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__SECRETS__BACKEND: airflow.secrets.local_filesystem.LocalFilesystemBackend
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_file_path":"/opt/airflow/secrets.json"}'
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: True
    command: >
      bash -c "
        airflow scheduler & 
        airflow webserver -p 8080 &
        sleep 10 &&
        airflow variables import /opt/airflow/secrets.json &&
        wait
      "
